filetype off
let g:mapleader = ","

nmap <Leader>ds  <Plug>DumpDebugStringVar
nmap <Leader>dS  <Plug>DumpDebugStringExpr

set runtimepath+=.
set runtimepath+=vader.vim
set runtimepath+=vim-repeat
set runtimepath+=after

filetype plugin indent on
syntax enable
set nomore
set noswapfile
set viminfo=
